image: ubuntu:18.04
stages:
    - deploy
deploy:
    stage: deploy
    only:
        refs:
            - master
    tags:
        - deploy
    before_script:
      - apt-get update -qy
      - apt-get install -y lftp
    script:
    - lftp -c "set ftp:ssl-allow no; open -u i426146, MediaBazarWeb hera.fhict.nl; mirror -Rev dist/ ./public_html  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"